# 配置文件

DAILY_TIME: "08:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-08-06" # 纪念日
CITY: "北京"

BIRTHDAY:
  - "11-09"

APP_ID: "wxf1989994d69e85a6"
APP_SECRET: "696d64f4f8dd462b9de66748c008a524"

USER_ID: 
  - "o2XE562rioPXocQqhD4ZU7rHmwMA"
TEMPLATE_ID: "m6anflATMVmqbXq87_yT3_MSs5KQY58W_QXjI52cgqI"
